service: domain
frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-iam-roles-per-function

custom:
  domainName: yanmifeakeju.link

resources:
  Resources:
    PublicHostedZone:
      Type: AWS::Route53::HostedZone
      Properties:
        Name: ${self:custom.domainName}
    DomainCert:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: ${self:custom.domainName}
        ValidationMethod: DNS
        DomainValidationOptions:
          - DomainName: ${self:custom.domainName}
            HostedZoneId: !Ref PublicHostedZone
  Outputs:
    DomainCertArn:
      Description: ARN of the domain root certificate
      Value: !Ref DomainCert
      Export:
        Name: domain-cert-${sls:stage}

    PublicHostedArn:
      Description: HostedZone for the domain
      Value: !Ref PublicHostedZone
      Export:
        Name: public-hosted-zone-${sls:stage}
