service: notification-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  region: 'us-east-1'
  profile: serverless
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - ${file(iam/SendMailIAM.yml):SendMailIAM}

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/sendMail.handler
    events:
      - sqs:
          batchSize: 1
          maximumRetryAttempts: 2
          arn: ${self:custom.MailQueue.arn}

custom:
  MailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
